# This Travis-CI integration uses ROS industrial_ci to perform unit- and node-level tests
# using catkin_make run_tests.
#
#    https://github.com/ros-industrial/industrial_ci
#
# The tests to run are specified in the project's CMakeLists.txt at the end
# in the "Testing" section.
# 
# Unit tests:
#
#   ## Add folders to be run by python nosetests
#   catkin_add_nosetests(tests/my_unit_test.py)
#
# Node tests:
#
#   # Node-level tests
#   if(CATKIN_ENABLE_TESTING)
#     find_package(rostest REQUIRED)
#     add_rostest(launch/node-level.test)
#   endif()
#

sudo: required 
dist: trusty 

language: generic 
compiler:
  - gcc
python:
  - "2.7"

env:
  global:
    - BEFORE_SCRIPT='./scripts/extend_rosdep.sh'
  matrix:
    - USE_DEB=true  ROS_DISTRO="kinetic"   ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu

install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config

script: 
  - source .ci_config/travis.sh
