language: python
python: 3.7

servies: docker

env:
  - DOCKER_TAG=sheaffej/b2-base:$TRAVIS_BRANCH

jobs:
  include:
    - arch: amd64
      install: docker build -t "$DOCKER_TAG" -f Dockerfile .
    # - arch: arm64
    #   install: docker build -t "$DOCKER_TAG" -f Dockerfile.arm .

script: 
  - scripts/run_dev_tests.sh nomount coveralls

deploy:
  provider: script
  script:
    - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push "$DOCKER_TAG"
  on:
    branch:
      - master
      - dev
      - docker