language: python
python: 3.7

servies: docker

jobs:
  include:
    - arch: amd64
      install: docker build -t b2-base -f Dockerfile .
    # - arch: arm64
    #   install: docker build -t b2-base -f Dockerfile.arm .


script: 
  - scripts/run_dev_tests.sh nomount coveralls

deploy:
  provider: script
  script: scripts/travis_deploy_dockerhub.sh
  # on:
  #   branch:
  #     - master
  #     - dev
  #     - docker