language: python
python: 3.7

servies: docker

jobs:
  include:
    - arch: amd64
    - arch: arm64

env:
  - DOCKER_IMAGE="b2-base"

install: docker build -t $DOCKER_IMAGE -f Dockerfile .

script: 
  - scripts/run_dev_tests.sh nomount coveralls

# deploy:
#   - provider: script
#     script: docker/travis_deploy_dockerhub.sh
#     on:
#       all_branches: true
#       condition: $TRAVIS_BRANCH == "master" || $TRAVIS_BRANCH == "dev"
