language: python
python: 3.7

servies: docker

jobs:
  include:
    - arch: amd64
      install: docker build -t b2-base Dockerfile
    - arch: arm64
      install: docker build -t b2-base Dockerfile.arm

# install:
#   - docker build -t b2-base $DOCKERFILE

script: 
  - scripts/run_dev_tests.sh nomount coveralls
